1.

In [ ]:
import numpy as np

arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


2

In [3]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])        # method 1
print(arr)

ar=np.arange(1,10).reshape(3,3)                # method 2
print("\n",ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


3

In [ ]:
import numpy as np

arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4

In [6]:
import numpy as np

a=np.random.rand(10)
print(a)

[0.42636976 0.66592387 0.04930275 0.90850853 0.63189659 0.65854679
 0.10680198 0.45855731 0.89581711 0.57594584]


5

In [ ]:
import numpy as np

a=np.zeros(10)
print(a)

b=np.ones(10)
print("\n",b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


6

In [ ]:
import numpy as np

a=np.array([10,20,30,40,50])
print(a[2])

30


7

In [ ]:
import numpy as np

a=np.array([[2,3,4,5],[6,7,8,9],[1,2,3,4],[4,3,2,1]])

print(a)
print("\n",a[1,2])

[[2 3 4 5]
 [6 7 8 9]
 [1 2 3 4]
 [4 3 2 1]]

 8


8

In [ ]:
import numpy as np

a=np.array([5,10,15,20,25])

print(a[4])

25


9

In [19]:
import numpy as np

ar=np.array([1,3,5,7,9,11])

print(ar[[1,3,4]])



[3 7 9]


10

In [ ]:
import numpy as np

a=np.array([[[5,4],[2,3]],
            [[7,8],[9,3]]])

print(a)
print("\n",a[1,1,1])

[[[5 4]
  [2 3]]

 [[7 8]
  [9 3]]]

 3


11

In [ ]:
import numpy as np

a=np.array([2,4,6,8,10,12])
print(a[0:3])

[2 4 6]


12

In [ ]:
import numpy as np

a=np.array([[2,3,4,5],[6,7,8,9],[1,2,3,4],[4,3,2,1]])

print(a)
print('')
print(a[:2,2:])

[[2 3 4 5]
 [6 7 8 9]
 [1 2 3 4]
 [4 3 2 1]]

[[4 5]
 [8 9]]


13

In [20]:
import numpy as np

a=np.array([0,1,2,3,4,5,6,7,8,9])

print(a[::2])

[0 2 4 6 8]


14

In [ ]:
import numpy as np

a=np.array([[2,3,4,5],[7,6,5,4],[8,9,4,5]])

print(a)
print('')

print(a[0:,2:])

[[2 3 4 5]
 [7 6 5 4]
 [8 9 4 5]]

[[4 5]
 [5 4]
 [4 5]]


15

In [ ]:
import numpy as np

a=np.array([[4,5,6,7,8],[9,8,7,6,5],[4,5,4,3,2],[1,2,3,4,5],[6,4,8,6,7]])

print(a)

print('')

print(a[1:4,1:4])

[[4 5 6 7 8]
 [9 8 7 6 5]
 [4 5 4 3 2]
 [1 2 3 4 5]
 [6 4 8 6 7]]

[[8 7 6]
 [5 4 3]
 [2 3 4]]


16

In [ ]:
import numpy as np

a=np.array([0,1,2,3,4,5])

print(a)

print('')

b=a.astype('f')
print(b)
print(b.dtype)

[0 1 2 3 4 5]

[0. 1. 2. 3. 4. 5.]
float32


17

In [22]:
import numpy as np

a=np.array([[0,1,1],[0,0,1],[1,1,0]])                                             # method 1

print(a)

print('')

b=a.astype(bool)
print(b)

r=np.array([False,True,True,False,False,True,True,True,False]).reshape(3,3)       # method 2
print("\n",r)

[[0 1 1]
 [0 0 1]
 [1 1 0]]

[[False  True  True]
 [False False  True]
 [ True  True False]]

 [[False  True  True]
 [False False  True]
 [ True  True False]]


18

In [13]:
import numpy as np

a=np.array([1+2j,3+4j,5+6j])


print(a)

[1.+2.j 3.+4.j 5.+6.j]


19

In [14]:
import numpy as np

a=np.array(["1","2","3"])
b=a.astype('i')
print(b)

[1 2 3]


20

In [15]:
import numpy as np

a=np.array([3.45,2.1,6.7,8.9])
b=a.astype('i')
print(b)

[3 2 6 8]
